---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
# !!! this "update all packages" has intentionally been commented out !!!
# The amount of updates takes ~25 minutes and Terraform crashes out
#  pre_tasks:
#    - name: update all packages
#      yum:
#        name: "*"
#        state: latest
  roles:
    - httpserver
